### PR TITLE
Cherry-pick commits from 6.4.x branch

### PR DESCRIPTION
**Pull request by bbrodt**

### CODE REVIEW

**Comment by mswiderski** [comment]
@krisv do you mind taking a look or shall it be merged directly as they are back ports?

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Pull request closed without merging**
